name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build
        run: |
          npm install
          npm run build -- --public-url https://parabole.servegame.com/pr-preview/pr-${{ github.event.number }}

      - name: Deploy preview
        if: github.event.action != 'closed'
        uses: rossjrw/pr-preview-action@v1.4.7
        with:
          umbrella-dir: pr-preview
          action: auto
          source-dir: dist

      - name: Cleanup deployment
        uses: rossjrw/pr-preview-action@v1.4.7
        if: github.event.action == 'closed' || github.event.pull_request.merged
        with:
          umbrella-dir: pr-preview
          action: remove
          source-dir: dist
